// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_bO6Qs1wadhUy2oWHDKBT3P9KIH9EI60',
    appId: '1:579055527097:web:a670a2b7a83b895dd9e768',
    messagingSenderId: '579055527097',
    projectId: 'expense-tracker-4da2b',
    authDomain: 'expense-tracker-4da2b.firebaseapp.com',
    storageBucket: 'expense-tracker-4da2b.firebasestorage.app',
    measurementId: 'G-QFVCMGEF8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh1pMCicvH-p70jmGybVRjRabrM_CtnC0',
    appId: '1:579055527097:android:1ffd41d14225efdfd9e768',
    messagingSenderId: '579055527097',
    projectId: 'expense-tracker-4da2b',
    storageBucket: 'expense-tracker-4da2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkdq16s2bWvD-XTKREaHPB5p243x_QzNE',
    appId: '1:579055527097:ios:648c2aadfdaa367ed9e768',
    messagingSenderId: '579055527097',
    projectId: 'expense-tracker-4da2b',
    storageBucket: 'expense-tracker-4da2b.firebasestorage.app',
    iosBundleId: 'com.example.expensetracker',
  );
}
